version: '3.8'
services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - '3002:3000'
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_ESLINT_DISABLED: true

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    command: npm run dev
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next