version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"                            # Optional: access to the Traefik dashboard
      - "--api.dashboard=true"
      - "--providers.docker=true"                        # Enable Docker as a provider
      - "--entrypoints.web.address=:80"                  # HTTP entrypoint
      - "--entrypoints.websecure.address=:443"           # HTTPS entrypoint
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"  # Enable TLS challenge for Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.email=i.munoz.repetto@gmail.com"  # Replace with your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Store the certs in this file
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Give Traefik access to Docker socket
      - "./letsencrypt:/letsencrypt"                    # Store SSL certificates here
    restart: always


  api:
    image: python:latest
    restart: always
    ports:
      - "8000:8000"
    container_name: api
    networks:
      - web
      - db
      - mqtt
    volumes:
      - ./api:/app
    command: sh -c "pip install -r /app/requirements.txt && python /app/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`frostback.earth`)"   # Replace with your domain
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=80" # Replace with your container's internal port


  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    networks:
      db:
        aliases:
          - postgres.local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    container_name: mosquitto
    networks:
      mqtt:
        aliases:
          - mosquitto.local
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

networks:
  web:
  db:
  mqtt:

volumes:
  api:
  postgres:
  mosquitto:
  letsencrypt:
