services:
  api:
    image: python:latest
    restart: always
    ports:
      - "4000:4000"
    networks:
      - db
      - mqtt
    volumes:
      - ./api:/app
    command: sh -c "pip install -r requirements.txt && python main.py"

  postgres:
    image: postgres:latest
    restart: always
    networks:
      - db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtt
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

networks:
  db:
  mqtt:

volumes:
  api:
  postgres:
  mosquitto: