# Generated by Django 5.1.1 on 2024-10-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianPositionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('altitude', models.BigIntegerField()),
                ('latitude_i', models.BigIntegerField()),
                ('longitude_i', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuardianTelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('barometric_pressure', models.DecimalField(decimal_places=12, max_digits=15)),
                ('relative_humidity', models.DecimalField(decimal_places=12, max_digits=15)),
                ('temperature', models.DecimalField(decimal_places=12, max_digits=15)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
