# Generated by Django 5.1.1 on 2024-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostguard_api', '0002_guardianzone_alter_guardianpositiondata_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianalert',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
