# Generated by Django 5.1.1 on 2024-10-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostguard_api', '0003_guardianalert_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianzone',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='guardianzone',
            name='crop_type',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='guardianzone',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='guardianzone',
            name='has_fans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardianzone',
            name='has_heaters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardianzone',
            name='has_roof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardianzone',
            name='has_sprinklers',
            field=models.BooleanField(default=False),
        ),
    ]
