# Generated by Django 5.1.1 on 2024-10-06 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostguard_api', '0004_guardianzone_coordinates_guardianzone_crop_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('guardian_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_contact', to='frostguard_api.guardianzone')),
            ],
        ),
    ]
