# Generated by Django 5.1.1 on 2024-10-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostguard_api', '0005_zonecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianpositiondata',
            name='latitude_i',
            field=models.DecimalField(decimal_places=12, max_digits=30),
        ),
        migrations.AlterField(
            model_name='guardianpositiondata',
            name='longitude_i',
            field=models.DecimalField(decimal_places=12, max_digits=30),
        ),
    ]
