# Generated by Django 5.1.1 on 2024-10-06 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostguard_api', '0006_alter_guardianpositiondata_latitude_i_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('control_type', models.CharField(choices=[('aspersion', 'Aspersión'), ('roof', 'Techo'), ('heater', 'Calefactor'), ('fan', 'Ventilador')], default='aspersion', max_length=20)),
                ('guardian_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_method', to='frostguard_api.guardianzone')),
            ],
        ),
    ]
